# Generated by Django 4.0.4 on 2022-05-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
